"""
General Processor - Cloud Agent
Handles unclassified tasks using Claude reasoning
"""

from datetime import datetime
from typing import Optional, Dict, Any

from src.config import VaultPaths, CLOUD_CONFIG
from src.utils.logging_utils import setup_logging, log_action, log_error
from src.utils.file_ops import write_task_file

logger = setup_logging()


def generate_plan_using_claude(
    task_type: str,
    context: str
) -> Optional[Dict[str, Any]]:
    """
    Generate an intelligent plan/draft for unclassified task using Claude

    Args:
        task_type: Type of task (from metadata)
        context: Full task content

    Returns:
        Dict with plan data, or None if failed
    """
    try:
        import anthropic

        client = anthropic.Anthropic(api_key=CLOUD_CONFIG["anthropic_api_key"])

        prompt = f"""You are an intelligent task planning assistant. Analyze this task and generate a detailed action plan:

Task Type: {task_type}
Task Details:
{context}

Generate a comprehensive plan that includes:
1. Summary of the task
2. Key objectives
3. Recommended actions (step by step)
4. Potential risks or considerations
5. Success criteria

Format your response as:
SUMMARY: [1-2 sentence summary]
OBJECTIVES: [Bulleted list]
ACTIONS: [Numbered step-by-step plan]
RISKS: [Key risks to consider]
SUCCESS_CRITERIA: [How to measure success]

Be specific and actionable."""

        message = client.messages.create(
            model="claude-opus-4-6",
            max_tokens=1000,
            messages=[
                {"role": "user", "content": prompt}
            ]
        )

        plan = {
            "task_type": task_type,
            "content": message.content[0].text,
            "generated_at": datetime.utcnow().isoformat(),
            "context": context[:200],  # Store first 200 chars for reference
        }

        logger.info(f"✅ Plan generated for {task_type}")
        log_action(
            "general_plan_generated",
            task_type,
            "success",
            {"context_length": len(context)}
        )

        return plan

    except Exception as e:
        logger.error(f"Failed to generate plan: {e}")
        log_error(
            "plan_generation_failed",
            str(e),
            {"task_type": task_type}
        )
        return None


def create_approval_request(
    plan: Dict[str, Any],
    source_file: str,
    task_type: str
) -> Optional[str]:
    """
    Create approval request file for generated plan

    Args:
        plan: Generated plan data
        source_file: Original source filename
        task_type: Type of task

    Returns:
        Path to created approval file, or None if failed
    """
    try:
        metadata = {
            "type": "approval_request",
            "action": "execute_plan",
            "domain": "general",
            "task_type": task_type,
            "source_file": source_file,
            "created": datetime.utcnow().isoformat(),
            "status": "pending_local_review",
            "agent": "cloud",
            "priority": "normal",
            "confidence": 0.80,
        }

        content = f"""## Task Plan

**Task Type**: {task_type}

### Claude-Generated Plan

{plan['content']}

---

## Actions

**To Approve**: Move to `/Approved/general/` on LOCAL machine
**To Reject**: Move to `/Rejected/` folder
**To Edit**: Modify content above before approving

---

⚠️ Generated by Cloud Agent - Review recommended before execution
Local Agent will proceed with approved actions.
"""

        approval_path = VaultPaths.PENDING_APPROVAL_GENERAL / f"PLAN_{datetime.now().strftime('%Y%m%d_%H%M%S')}.md"

        success = write_task_file(approval_path, metadata, content)

        if success:
            logger.info(f"✅ Approval request created: {approval_path.name}")
            return str(approval_path)
        else:
            logger.error("Failed to write approval request")
            return None

    except Exception as e:
        logger.error(f"Failed to create approval request: {e}")
        log_error(
            "approval_request_creation_failed",
            str(e)
        )
        return None


def process_general_task(task_file: str) -> bool:
    """
    Process general task: generate plan + create approval request

    Args:
        task_file: Path to task file

    Returns:
        True if successful
    """
    try:
        from src.utils.file_ops import read_task_file

        task_data = read_task_file(task_file)
        if not task_data:
            return False

        metadata = task_data.get("metadata", {})
        content = task_data.get("content", "")

        task_type = metadata.get("type", "general")

        if not content:
            logger.error("General task missing content")
            return False

        # Generate plan using Claude
        plan = generate_plan_using_claude(task_type, content)
        if not plan:
            return False

        # Create approval request
        approval_path = create_approval_request(plan, task_file, task_type)
        return approval_path is not None

    except Exception as e:
        logger.error(f"Failed to process general task: {e}")
        log_error(
            "process_general_task_failed",
            str(e),
            {"task_file": task_file}
        )
        return False
